#!/usr/bin/env python
from argparse import ArgumentParser
# from area27 import generate_signal, link_it_up

p = ArgumentParser()
p.add_argument("-t", "--toolstable", 
            dest="toolstable",
            metavar="TOOLSFILE",
            help="Tools file")
p.add_argument("-s", "--samplestable", 
            dest="samplestable",
            metavar="SAMPLESFILE",
            help="Samples file")
p.add_argument("-o", "--outfile", 
            dest="outfile",
            metavar="OUTFILE",
            help="Output file")
p.add_argument("-N", "--nthreads",
            dest="nthreads",
            type=int,
            metavar="THREADS",
            help="Number of threads")
            
args = p.parse_args()

# signal = generate_signal(args.bamfile, window=2000, nthreads=args.nthreads)
# link_it_up(args.outfile, signal)
